package com.armatura.internaldata.fragment

import android.os.Bundle
import android.view.LayoutInflater
import android.view.View
import android.view.ViewGroup
import androidx.lifecycle.lifecycleScope
import com.armatura.biomodule.R
import com.armatura.biomodule.common.RegisterType
import com.armatura.biomodule.databinding.FragmentModuleRegisterByInternalBinding
import com.armatura.biomodule.dialog.ProgressDialogFragment
import com.armatura.biomodule.view.ToolBar
import com.armatura.internaldata.viewmodel.ModuleUserMgnViewModel
import kotlinx.coroutines.launch

/**
 * Created by Jeremy on 2022/11/4.
 * This page is used to demonstrate how to use the image generated by the module to add faces/palms
 * to existing users in the module without transmitting any data.
 * Not all modules support this function, please consult business.
 */
class ModuleRegByInternalFragment : RegisterBaseFragment() {
    private var title: String? = null
    private var type: Int = 0
    private var userId: String = ""
    private var operate: Int = 0
    private lateinit var binding: FragmentModuleRegisterByInternalBinding
    private lateinit var viewModel: ModuleUserMgnViewModel
    private var loadingDialog: ProgressDialogFragment? = null

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        viewModel = getAndroidViewModel(ModuleUserMgnViewModel::class.java)
        val bundle = requireArguments()
        title = bundle.getString(REGISTER_TITLE)
        type = bundle.getInt(REGISTER_TYPE)
        userId = bundle.getString(REGISTER_USER_ID).toString()
        operate = bundle.getInt(REGISTER_OPERATE)
        viewModel.setRegisterOperate(userId, type, operate)

        viewModel.registerFinishLiveData.observe(this) {
            if (it) {
                lifecycleScope.launch {
                    activity?.onBackPressedDispatcher?.onBackPressed()
                }
            }
        }

        viewModel.progressLiveData.observe(this) {
            binding.registerProgressBar.incrementProgressBy(it)
        }

        viewModel.statusLiveData.observe(this) {
            if (it.isNotEmpty()) {
                binding.registerStatusTv.text = it
            }
            dismissDialog()
        }

        viewModel.toastMsgLiveData.observe(this) {
            showToastMsg(it)
        }
    }

    override fun onCreateView(
        inflater: LayoutInflater,
        container: ViewGroup?,
        savedInstanceState: Bundle?,
    ): View {
        binding = FragmentModuleRegisterByInternalBinding.inflate(inflater, container, false)
        return binding.root
    }

    override fun onViewCreated(view: View, savedInstanceState: Bundle?) {
        super.onViewCreated(view, savedInstanceState)
        binding.topToolBar.setTitle(title)
        binding.topToolBar.setToolBarClickListener(object : ToolBar.ToolBarClickListener {
            override fun onClickLeft() {
                activity?.onBackPressedDispatcher?.onBackPressed()
            }

            override fun onClickRight() {}
        })

        binding.registerProgressBar.max = if (type == RegisterType.FACE) 100 else 600
        binding.selectImgBtn.setOnClickListener {
            showLoadingDialog()
        }

    }

    override fun onDestroy() {
        viewModel.resetConfigs()
        dismissDialog()
        super.onDestroy()
    }

    private fun showLoadingDialog(message: String = getString(R.string.snapshot)) {
        ProgressDialogFragment.show(parentFragmentManager, "", message, true).also {
            loadingDialog = it
        }
    }

    private fun dismissDialog() {
        loadingDialog?.dismiss(parentFragmentManager)
    }

    companion object {
        private const val REGISTER_TYPE = "type"
        private const val REGISTER_TITLE = "title"
        private const val REGISTER_USER_ID = "userId"
        private const val REGISTER_OPERATE = "operate"
        private const val TAG = "MRegByInternalFragment"

        @JvmStatic
        fun newInstance(
            type: Int,
            title: String?,
            userId: String?,
            operate: Int,
        ): ModuleRegByInternalFragment {
            val fragment = ModuleRegByInternalFragment()
            fragment.arguments = Bundle().apply {
                putInt(REGISTER_TYPE, type)
                putString(REGISTER_TITLE, title)
                putString(REGISTER_USER_ID, userId)
                putInt(REGISTER_OPERATE, operate)
            }
            return fragment
        }
    }
}